version: 2.1
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.14
    parameters:
      tfvarsfile:
        type: string
        default: notspecified
    environment:
      - TF_VAR_aws_region: eu-west-1
      - tfstatebucket: circlecitfstate
      - tfstatedir: circledeployments
      - tfstateregion: us-east-2
    steps:
      - checkout
      - run:
          name: Make backend for << parameters.tfvarsfile >>
          command: |
            cat \<<EOF > backend_override.tf
              terraform {
                  backend "s3" {
                    bucket = "${tfstatebucket}"
                    key    = "${tfstatedir}/${CIRCLE_BUILD_NUM}-<< parameters.tfvarsfile >>.tfstate"
                    region = "${tfstateregion}"
                  }
                }
            EOF
      - run: terraform init
      - run:
          name: terraform plan
          command: terraform plan -var-file=<< parameters.tfvarsfile >> -out=mybuild
      - run:
          name: terraform apply
          command: terraform apply "mybuild"
      - run:
          name: terraform destroy
          command: terraform destroy -force
          when: always
workflows:
  workflow:
    jobs:
      - build:
          tfvarsfile: terraform-icp-ce-example.tfvars
      - build:
          requires:
            - build
          tfvarsfile: terraform-icp-ce-example.tfvars
      # Repeated as many times as there are configurations...
