version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.14
    steps:
      - checkout
      - run:
          name: Make backend
          command: |
            cat <<EOF > backend_override.tf
              terraform {
                  backend "s3" {
                    bucket = "${tfstatebucket}"
                    key    = "circledeployments/${CIRCLE_BUILD_NUM}"
                    region = "${tfstateregion}"
                  }
                }
            EOF
      - run:
          name: Terraform init
          command: terraform init
      - run:
          name: Plan ICP CE Ubuntu
          command: terraform plan -var-file=terraform-icp-ce-example.tfvars -out=icp-ce-ubuntu
      - run:
          name: Deploy and destroy ICP CE Ubuntu
          command: |
            set +e
            terraform apply icp-ce-ubuntu
            aplyval=$?
            terraform destroy -force
            return ${aplyval}
      - run:
          name: Plan ICP CE RHEL
          command: terraform plan -var-file=terraform-icp-ce-rhel-example.tfvars -out=icp-ce-rhel
      - run:
          name: Deploy and destroy ICP CE RHEL
          command: |
            set +e
            terraform apply icp-ce-rhel
            aplyval=$?
            terraform destroy -force
            return ${aplyval}
